# Generated by Django 2.0.2 on 2018-02-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('ph_number', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
