# Generated by Django 2.0.2 on 2018-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ph_number',
            field=models.BigIntegerField(),
        ),
    ]
